CREATE TABLE IF NOT EXISTS job_ad (
  id SERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  category VARCHAR(255) NOT NULL,
  target VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  calary NUMERIC NOT NULL,
  description TEXT NOT NULL,
  skills TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
